name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Instalar ruff
        run: pip install ruff

      - name: Rodar lint
        run: ruff check .

      - name: Rodar testes
        run: python -m pytest